PontoSync/Models/Registro.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace PontoSync.Models
{
    [Table(name: "MARCACAO", Schema = "FORPON_RELG")]
    public class Registro
    {
        [Key]
        [Column(name:"ID")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        /// <summary>
        /// Chave no relógio do registro. Poderá se repetir entre diferentes relógios.
        /// </summary>
        [Column(name: "ID_MARCACAO_RELOGIO")]
        public String idMarcacaoRelogio {get;set;}
        [Column(name: "MATRICULA")]
        public String Matricula { get; set; }

        [Column(name: "MARCACAO")]
        public DateTime Marcacao { get; set; }

        [Column(name: "ID_RELOGIO")]
        public int IdRelogio { get; set; }

        [ForeignKey("IdRelogio")]
        [JsonIgnore]
        public Relogio Relogio { get; set; }
        
        [NotMapped]
        public bool Migrado
        {
            get { return MigradoFrequencia == "T"; }
            set { MigradoFrequencia = value ? "T" : "F"; }
        }

        [Column(name: "MIGRADO_FREQUENCIA")]
        public string MigradoFrequencia { get; set; } = "F";

    }
}

PontoSync/Controllers/RegistrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PontoSync.Data;
using PontoSync.Models;

namespace PontoSync.Controllers
{
    [Authorize]
    public class RegistrosController : Controller
    {
        private readonly PontoSyncContext _context;

        public RegistrosController(PontoSyncContext context)
        {
            _context = context;
        }

        // GET: Registros
        [HttpGet("{controller}/Index/{matricula?}/{Migrado?}")]
        public async Task<IActionResult> Index(String matricula = "", String Migrado = "")
        {

            var pontoSyncContext = _context.Registros.Include(r => r.Relogio).Where(p=> true);
            if (!String.IsNullOrEmpty(matricula))
            {
                ViewBag.Matricula = matricula.ToString();
                pontoSyncContext = pontoSyncContext.Where(ps => ps.Matricula.EndsWith(matricula.ToString()));
            }
            else
            {
                ViewBag.Matricula = "";
            }
            if(Migrado == "NMigrado")
            {
                pontoSyncContext = pontoSyncContext.Where(ps => ps.MigradoFrequencia == "F");
            }else if(Migrado == "Migrado")
            {
                pontoSyncContext = pontoSyncContext.Where(ps => ps.MigradoFrequencia == "T");
            }
            return View(await pontoSyncContext.OrderByDescending(ps=> ps.Marcacao).ToListAsync());
        }


        // GET: Registros/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var registro = await _context.Registros
                .Include(r => r.Relogio)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (registro == null)
            {
                return NotFound();
            }

            return View(registro);
        }

        // GET: Registros/Create
        public IActionResult Create()
        {
            ViewData["IdRelogio"] = new SelectList(_context.Relogios, "Id", "Id");
            return View();
        }  

     
       
        private bool RegistroExists(int id)
        {
            return _context.Registros.Any(e => e.Id == id);
        }
    }
}

PontoSync/Controllers/RelogiosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using PontoSync.Data;
using PontoSync.Models;
using PontoSync.Service;

namespace PontoSync.Controllers
{
    [Authorize]
    public class RelogiosController : Controller
    {
        private readonly PontoSyncContext _context;
        private readonly FrequenciaContext _frequenciaContext;
        private readonly ILogger<RelogiosController> _logger;
        private readonly IServiceProvider _serviceProvider;
        public RelogiosController(PontoSyncContext context, FrequenciaContext frequenciaContext, ILogger<RelogiosController> logger,
            IServiceProvider provider)
        {
            _context = context;
            _frequenciaContext = frequenciaContext;
            _logger = logger;
            _serviceProvider = provider;
        }

        // GET: Relogios
        public async Task<IActionResult> Index()
        {
            return View(await _context.Relogios.ToListAsync());
        }

        // GET: Relogios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            return await Details(id, DateTime.Now.AddDays(-7), DateTime.Now);
        }

        [Authorize(Policy = "GRUPO_AUTORIZACAO")]
        [HttpPost("{controller}/MigrarRegistros/{id}")]
        public async Task<IActionResult> MigrarIntervalo(int id, [FromBody] int[] registrosId)
        {

            if (id == null)
            {
                return NotFound();
            }           
            var relogio = await _context.Relogios.FindAsync(id);
            
            if(relogio == null)
            {
                return NotFound();
            }
            if(registrosId == null)
            {
                return BadRequest();
            }
            var registros = _context.Registros.Where(rg => rg.IdRelogio == id && registrosId.Contains(rg.Id)).ToList();

            IRelogioService relogioService = (IRelogioService)ActivatorUtilities.CreateInstance(this._serviceProvider, typeof(RelogioHenry));
            relogioService.LancarRegistros(relogio, registros);
            relogio.Registros = registros;
            return Ok();
        }


        [Authorize(Policy = "GRUPO_AUTORIZACAO")]
        public async Task<IActionResult> Migrar(int? id, int? idRegistro)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (idRegistro == null)
            {
                return NotFound();
            }
            try
            {
                var relogio = await _context.Relogios.FindAsync(id);
                var registro = await _context.Registros.FindAsync(idRegistro);
                if (registro == null)
                {
                    return NotFound();
                }
                IRelogioService relogioService = (IRelogioService)ActivatorUtilities.CreateInstance(this._serviceProvider, typeof(RelogioHenry));
                relogioService.LancarRegistro(relogio, registro);
                ViewBag.Fim = registro.Marcacao.Date;
                ViewBag.Inicio = registro.Marcacao.Date;
                return View("Details", relogio);
            }
            catch(Exception e)
            {
                _logger.LogError(e, $"Erro ao migrar Relógio {id} e o registro {idRegistro}");
                throw e;
            }

        }

        [Authorize(Policy = "GRUPO_AUTORIZACAO")]
        // GET: Relogios/Details/5
        [HttpGet("{controller}/Details/{id}/{Inicio?}/{Fim?}")]
        public async Task<IActionResult> Details(int? id, DateTime? Inicio, DateTime? Fim )
        {
            if (id == null)
            {
                return NotFound();
            }
            if (!Inicio.HasValue)
            {
                Inicio = DateTime.Now.AddDays(-3).Date;
            }
            if (!Fim.HasValue)
            {
                Fim = DateTime.Now.Date;
            }
            ViewBag.Fim =  Fim;
            ViewBag.Inicio = Inicio;
            var relogio = await _context.Relogios
                .FirstOrDefaultAsync(m => m.Id == id);
            try
            {
                IRelogioService relogioService = (IRelogioService)ActivatorUtilities.CreateInstance(this._serviceProvider, typeof(RelogioHenry));
                await relogioService.LerRelogioELancarAsync(relogio, Inicio.Value, Fim.Value.AddDays(1), lancar: false);

            }catch(Exception e)
            {
                _logger.LogError("Não foi possível ler o relógio. Mostrando dados adquiridos anteriormente");
            }
            relogio.Registros = _context.Registros.Where(r => r.IdRelogio == relogio.Id && r.Marcacao > Inicio && r.Marcacao < Fim).OrderBy(r => r.Marcacao).ToList();
            if (relogio == null)
            {
                return NotFound();
            }

            return View(relogio);
        }


        [Authorize(Policy = "GRUPO_AUTORIZACAO")]
        // GET: Relogios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Relogios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "GRUPO_AUTORIZACAO")]
        public async Task<IActionResult> Create([Bind("Id,URL,Nome,Descricao,UltimaLeitura,UltimoSucess,UltimaFalha,Usuario,Senha")] Relogio relogio)
        {
            if (ModelState.IsValid)
            {
                _context.Add(relogio);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(relogio);
        }

        // GET: Relogios/Edit/5
        [Authorize(Policy = "GRUPO_AUTORIZACAO")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var relogio = await _context.Relogios.Where(R => R.Id == id).FirstOrDefaultAsync();
            if (relogio == null)
            {
                return NotFound();
            }
            return View(relogio);
        }




        // POST: Relogios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "GRUPO_AUTORIZACAO")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,URL,Descricao,Nome,Usuario, Senha")] Relogio relogio)
        {
            if (id != relogio.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(relogio);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RelogioExists(relogio.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(relogio);
        }

        // GET: Relogios/Delete/5
        [Authorize(Policy = "GRUPO_AUTORIZACAO")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var relogio = await _context.Relogios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (relogio == null)
            {
                return NotFound();
            }

            return View(relogio);
        }

        // POST: Relogios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "GRUPO_AUTORIZACAO")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var relogio = await _context.Relogios.FindAsync(id);
            _context.Relogios.Remove(relogio);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RelogioExists(int id)
        {
            return _context.Relogios.Any(e => e.Id == id);
        }
    }
}

PontoSync/Views/Registros/Details.cshtml
@model PontoSync.Models.Registro

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Registro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.idMarcacaoRelogio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.idMarcacaoRelogio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Matricula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marcacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marcacao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Relogio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Relogio.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MigradoFrequencia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MigradoFrequencia)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PontoSync/Views/Registros/Index.cshtml
@model IEnumerable<PontoSync.Models.Registro>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            <h5>Matrícula</h5>
        </dt>
        <dd class="col-sm-10">
            <input id="matricula" type="text" class="form-control" value="@ViewBag.Matricula" />
        </dd>
        <dt class="col-sm-2">
            <h5>Migrados</h5>
        </dt>
        <dd class="col-sm-10">
            <select id="migrado" name="cars">
                <option value="NA">Todos</option>
                <option value="Migrado">Migrados</option>
                <option value="NMigrado">Não Migrados</option>
            </select>
        </dd>
    </dl>
    <a onclick="procurar();" class="btn btn-primary float-right" role="button">Visualizar</a>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.idMarcacaoRelogio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Matricula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marcacao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Relogio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MigradoFrequencia)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.idMarcacaoRelogio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Matricula)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Marcacao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Relogio.Descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MigradoFrequencia)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Migrar" asp-controller="Relogios" asp-route-id="@item.Relogio.Id" asp-route-idRegistro="@item.Id">Migrar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts{
    <script>
        function procurar(){
            window.location.href = "/Registros/Index/" + document.getElementById("matricula").value +
                "/" + document.getElementById("migrado").value;
        };

    </script>
}